# DAT213x Analyzing Big Data w Microsoft R
# Lab 1
See: https://github.com/danbeutler/r-server-introduction

In [3]:
nyc_xdf <- RxXdfData('C:/DAT213x/nyc_lab1.xdf')
rxGetInfo(nyc_xdf, getVarInfo = TRUE, numRows = 10)
rxSummary( ~ factor(RatecodeID, levels = 1:99) + 
             factor(payment_type, levels = 1:4), nyc_xdf)

File name: C:\DAT213x\nyc_lab1.xdf
Number of observations: 4012451
Number of variables: 30
Number of blocks: 7
Compression type: zlib
Variable information:
Var 1: VendorID
       2 factor levels: 2 1
Var 2: tpep_pickup_datetime, Type: character
Var 3: tpep_dropoff_datetime, Type: character
Var 4: passenger_count, Type: integer, Low/High: (0, 9)
Var 5: trip_distance, Type: numeric, Low/High: (0.0000, 12000004.5000)
Var 6: pickup_longitude, Type: numeric, Low/High: (-121.9333, 0.0000)
Var 7: pickup_latitude, Type: numeric, Low/High: (0.0000, 53.4046)
Var 8: RatecodeID, Type: integer, Low/High: (1, 99)
Var 9: store_and_fwd_flag
       2 factor levels: N Y
Var 10: dropoff_longitude, Type: numeric, Low/High: (-121.9333, 0.0000)
Var 11: dropoff_latitude, Type: numeric, Low/High: (0.0000, 50.7979)
Var 12: payment_type
       4 factor levels: 2 1 3 4
Var 13: fare_amount, Type: numeric, Low/High: (-376.0000, 2550.2000)
Var 14: extra, Type: numeric, Low/High: (-4.5000, 50.0100)
Var 15: mta_tax, Type: numeric, Low/High: (-1.0000, 3.0000)
Var 16: tip_amount, Type: numeric, Low/High: (-35.0000, 998.1400)
Var 17: tolls_amount, Type: numeric, Low/High: (-10.5000, 613.5000)
Var 18: improvement_surcharge, Type: numeric, Low/High: (-0.3000, 11.6400)
Var 19: total_amount, Type: numeric, Low/High: (-376.3000, 2551.0000)
Var 20: u, Type: numeric, Low/High: (0.0000, 0.0500)
Var 21: tip_percent, Type: numeric, Low/High: (0.0000, 99.0000)
Var 22: pickup_hour
       7 factor levels: 1AM-5AM 5AM-9AM 9AM-12PM 12PM-4PM 4PM-6PM 6PM-10PM 10PM-1AM
Var 23: pickup_dow
       7 factor levels: Sun Mon Tue Wed Thu Fri Sat
Var 24: dropoff_hour
       7 factor levels: 1AM-5AM 5AM-9AM 9AM-12PM 12PM-4PM 4PM-6PM 6PM-10PM 10PM-1AM
Var 25: dropoff_dow
       7 factor levels: Sun Mon Tue Wed Thu Fri Sat
Var 26: trip_duration, Type: integer, Low/High: (-8018875, 10764064)
Var 27: pickup_nhood
       263 factor levels: 19th Ward Abbott McKinley Albright Allen Annandale ... Woodhaven-Richmond Hill Woodlawn-Nordwood Woodrow Woodside Yorkville
Var 28: pickup_borough
       9 factor levels: Albany Buffalo New York City-Bronx New York City-Brooklyn New York City-Manhattan New York City-Queens New York City-Staten Island Rochester Syracuse
Var 29: dropoff_nhood
       263 factor levels: 19th Ward Abbott McKinley Albright Allen Annandale ... Woodhaven-Richmond Hill Woodlawn-Nordwood Woodrow Woodside Yorkville
Var 30: dropoff_borough
       9 factor levels: Albany Buffalo New York City-Bronx New York City-Brooklyn New York City-Manhattan New York City-Queens New York City-Staten Island Rochester Syracuse
Data (10 rows starting with row 1):
   VendorID tpep_pickup_datetime tpep_dropoff_datetime passenger_count
1         2  2016-01-01 00:00:00   2016-01-01 00:26:45               2
2         2  2016-01-01 00:00:17   2016-01-01 00:42:23               1
3         2  2016-01-01 00:00:36   2016-01-01 00:10:02               1
4         1  2016-01-01 00:00:37   2016-01-01 00:06:01               1
5         2  2016-01-01 00:01:29   2016-01-01 00:05:08               1
6         2  2016-01-01 00:01:37   2016-01-01 00:26:40               2
7         2  2016-01-01 00:01:41   2016-01-01 00:08:17               1
8         1  2016-01-29 09:18:26   2016-01-29 09:31:53               1
9         2  2016-01-29 09:18:26   2016-01-29 09:25:24               1
10        1  2016-01-29 09:18:33   2016-01-29 09:37:02               2
   trip_distance pickup_longitude pickup_latitude RatecodeID store_and_fwd_flag
1           7.45        -73.99406        40.71999          1                  N
2           2.32        -73.98166        40.77374          1                  N
3           1.61        -73.96375        40.77116          1                  N
4           1.20        -73.97602        40.74456          1                  N
5           0.76        -73.94185        40.82948          1                  N
6           4.59        -73.97367        40.78452          1                  N
7           1.33        -73.97645        40.75838          1                  N
8           1.50        -73.99271        40.75522          1                  N
9           0.52        -73.96844        40.79945          1                  N
10          1.50        -73.99022        40.75626          1                  N
   dropoff_longitude dropoff_latitude payment_type fare_amount extra mta_tax
1          -73.96636         40.78987            2        26.0   0.5     0.5
2          -73.99596         40.75384            2        19.0   0.5     0.5
3          -73.97560         40.75274            2         8.5   0.5     0.5
4          -73.96649         40.75366            1         6.5   0.5     0.5
5          -73.93864         40.83987            2         4.5   0.5     0.5
6          -73.98819         40.73197            2        19.0   0.5     0.5
7          -73.97643         40.74511            2         7.0   0.5     0.5
8          -73.99133         40.73881            1        10.0   0.0     0.5
9          -73.96644         40.79440            1         6.0   0.0     0.5
10         -73.98146         40.74522            1        12.5   0.0     0.5
   tip_amount tolls_amount improvement_surcharge total_amount         u
1         0.0            0                   0.3         27.3 0.0067058
2         0.0            0                   0.3         20.3 0.0117652
3         0.0            0                   0.3          9.8 0.0458733
4         2.3            0                   0.3         10.1 0.0330025
5         0.0            0                   0.3          5.8 0.0398959
6         0.0            0                   0.3         20.3 0.0054758
7         0.0            0                   0.3          8.3 0.0229865
8         1.0            0                   0.3         11.8 0.0062850
9         1.0            0                   0.3          7.8 0.0019004
10        1.0            0                   0.3         14.3 0.0168434
   tip_percent pickup_hour pickup_dow dropoff_hour dropoff_dow trip_duration
1            0    10PM-1AM        Fri     10PM-1AM         Fri          1605
2            0    10PM-1AM        Fri     10PM-1AM         Fri          2526
3            0    10PM-1AM        Fri     10PM-1AM         Fri           566
4           35    10PM-1AM        Fri     10PM-1AM         Fri           324
5            0    10PM-1AM        Fri     10PM-1AM         Fri           219
6            0    10PM-1AM        Fri     10PM-1AM         Fri          1503
7            0    10PM-1AM        Fri     10PM-1AM         Fri           396
8           10     5AM-9AM        Fri      5AM-9AM         Fri           807
9           17     5AM-9AM        Fri      5AM-9AM         Fri           418
10           8     5AM-9AM        Fri      5AM-9AM         Fri          1109
       pickup_nhood          pickup_borough      dropoff_nhood
1   Lower East Side New York City-Manhattan    Upper West Side
2   Upper West Side New York City-Manhattan            Clinton
3   Upper East Side New York City-Manhattan            Midtown
4          Gramercy New York City-Manhattan            Midtown
5            Harlem New York City-Manhattan Washington Heights
6   Upper West Side New York City-Manhattan       East Village
7           Midtown New York City-Manhattan           Gramercy
8           Clinton New York City-Manhattan           Gramercy
9   Upper West Side New York City-Manhattan    Upper West Side
10 Garment District New York City-Manhattan           Gramercy
           dropoff_borough
1  New York City-Manhattan
2  New York City-Manhattan
3  New York City-Manhattan
4  New York City-Manhattan
5  New York City-Manhattan
6  New York City-Manhattan
7  New York City-Manhattan
8  New York City-Manhattan
9  New York City-Manhattan
10 New York City-Manhattan

Rows Read: 4012451, Total Rows Processed: 4012451, Total Chunk Time: 0.995 seconds
Computation time: 1.666 seconds.

Call:
rxSummary(formula = ~factor(RatecodeID, levels = 1:99) + factor(payment_type,
    levels = 1:4), data = nyc_xdf)

Summary Statistics Results for: ~factor(RatecodeID, levels = 1:99) +
    factor(payment_type, levels = 1:4)
Data: nyc_xdf (RxXdfData Data Source)
File name: C:/DAT213x/nyc_lab1.xdf
Number of valid observations: 4012451


Category Counts for factor.RatecodeID..levels...1.99.
Number of categories: 99
Number of valid observations:
Number of missing observations:

 factor.RatecodeID..levels...1.99. Counts
 1                                 3904967
 2                                   85396
 3                                    7312
 4                                    1789
 5                                   12442
 6                                      34
 7                                       0
 8                                       0
 9                                       0
 10                                      0
 11                                      0
 12                                      0
 13                                      0
 14                                      0
 15                                      0
 16                                      0
 17                                      0
 18                                      0
 19                                      0
 20                                      0
 21                                      0
 22                                      0
 23                                      0
 24                                      0
 25                                      0
 26                                      0
 27                                      0
 28                                      0
 29                                      0
 30                                      0
 31                                      0
 32                                      0
 33                                      0
 34                                      0
 35                                      0
 36                                      0
 37                                      0
 38                                      0
 39                                      0
 40                                      0
 41                                      0
 42                                      0
 43                                      0
 44                                      0
 45                                      0
 46                                      0
 47                                      0
 48                                      0
 49                                      0
 50                                      0
 51                                      0
 52                                      0
 53                                      0
 54                                      0
 55                                      0
 56                                      0
 57                                      0
 58                                      0
 59                                      0
 60                                      0
 61                                      0
 62                                      0
 63                                      0
 64                                      0
 65                                      0
 66                                      0
 67                                      0
 68                                      0
 69                                      0
 70                                      0
 71                                      0
 72                                      0
 73                                      0
 74                                      0
 75                                      0
 76                                      0
 77                                      0
 78                                      0
 79                                      0
 80                                      0
 81                                      0
 82                                      0
 83                                      0
 84                                      0
 85                                      0
 86                                      0
 87                                      0
 88                                      0
 89                                      0
 90                                      0
 91                                      0
 92                                      0
 93                                      0
 94                                      0
 95                                      0
 96                                      0
 97                                      0
 98                                      0
 99                                    511

Category Counts for factor.payment_type..levels...1.4.
Number of categories: 4
Number of valid observations:
Number of missing observations:

 factor.payment_type..levels...1.4. Counts
 1                                  2658588
 2                                  1332777
 3                                    15651
 4                                     5435